### PR TITLE
Fix issue #5

### PR DESCRIPTION
**Pull request by MParrao**
This code solves the issue #5 also was included the first commit for the integration tests of the plugin.

### CODE REVIEW

**Comment by jgawor** [comment]
A couple of comments:
1) In terms of tests, that's a good start. However, see if there is a way to write an integration tests in such a way that the tests are actually invoking some test.gradle project. See how the integration tests are done in ci.ant or ci.maven

2) Changes to deploy/undeploy are ok but think about supporting multiple applications at the same time. Also naming parameters filePath and fileName is pretty generic and it's hard to see what that will be used for when just looking at a sample .gradle file. Maybe something to consider is "application" or "deployable" type of object for specifying application - see https://github.com/bmuschko/gradle-cargo-plugin as an example.

**Comment by oscarlv** [comment]
@jgawor I've already review what you mentioned but I the "deployable" type it was not defined in the groovy project of the cargo plugin, it was done in the the ant plugin see here - http://cargo.codehaus.org/Ant+support , so to copy this type of object we must to modify the ant tasks to use "deployable" instead of file, fileset, etc. Is that correct?

**Comment by MParrao** [comment]
Maybe this could be done using the file, fileSet and patternSet types directly instead of modifying the deploy/undeploy tasks, also this would make the plugins to be more standarized

**Comment by MParrao** [comment]
I think something like this could help MParrao/ci.gradle@e41b42604729aca5345ec744e36e5429c06c8290  This would allow the user to manipulate better the includes and excludes respective for each task.
For example the user could
```groovy
fileSet = ant.fileset(dir:"src", includes:"**/*.war")
     or
fileSet.setIncludes("**/*.war")
```
Just for giving an example. This will also work with patternset

**Pull request closed without merging**
