### PR TITLE
V3.0 first Commit

### PR DESCRIPTION
**Pull request by scphantm**
This is the first commit for V3.  This includes almost a complete rewrite of the core of this plugin.  this is now structured like a gradle plugin.  

You are not going to be able to run the tests yet.  I have to work with the developer of the test wrapper to fix a few things, then you can run it.  But i wanted to get this out here so people can start looking at it.  tests and documentation are the big things that need done.  I recommend you guys create a 3.0 snapshot branch and this merge into that branch instead of master, until everything is ironed out.

### CODE REVIEW

**Comment by scphantm** [comment]
This initial release of 3.0 is coming along slowly.  I have most of the structural problems with the original code worked out, things broken out more, things modularized.  I am almost (ALMOST) done converting the unit tests to GradleTest.  That fixes problems that were in the original unit suite, primarily it looked like the integration tests were written before TestKit was released, so a TON of unnecessary code was in there.  GradleTest is a wrapper for TestKit that simply makes it easier to write tests.  

When the tests are converted, I have some legacy 2.x code to bring back to life (mainly the app install via app() setting) and there are several that im going to need your guys/gals help with as i think the problems exist in the ant library, not gradle

This MR is already huge.  Please create a `3.0dev` or something branch so we can get this code merged in and start taking on smaller MR's.  hopefully get other people involved too, my company has already spent many thousands of dollars of my time getting this plugin this far, im going to need help with some of the fine polishing.

**Comment by mattbsox** [comment]
Thanks for these changes. We'll start going through them and get the PR into the new branch.

**Comment by scphantm** [comment]
why was this closed without merging?

**Comment by chyt** [comment]
Sorry, we accidentally deleted the branch that this PR was merged to. We restored the branch but I didn't notice that it also automatically closed the PR. It's been re-opened.

**Comment by scphantm** [comment]
ok, scared me there.  This is still going to fail tests saying it can't find gradleTest.  Developer of that library should be cutting a new alpha of it today.  I have been working with him to add some features to make that a bit cleaner as well.  When he cuts a new alpha, ill fix these merge conflicts that are popping up as well.

**Comment by scphantm** [comment]
Ok, the tests are officially converted.  Other changes are pulled in.

about half of the tests are going to blow up.  Primarily because the install app task is only half re-implemented.  

I am working on 3 other high priority projects in addition to this one, so my time is limited.  Im got the approval to hire a new developer to finish this today, i should start interviewing next week.  I am going to work on this as i have time.

This should now build and kinda run, so you can merge it into the dev 3 branch, just so we can start making the MR's smaller.  I'm going to see how tonight goes, i may be able to reimplement some of the `installapp` before i have to leave for work in the morning.

**Pull request merged**
